### ISSUE TITLE
Inital build for hugo site

### ISSUE THREAD

**Issue by stim-ca** [stim-ca/blog.ShawnTimewell.ca#3]
## Tasks

- [ ]  deploy the getting started Hugo site to github pages
- [ ]  configure github actions to build site when changes have been made
- [ ] configure the https://github.com/vaga/hugo-theme-m10c theme
- [ ]  write intro blog post
